# Generated by Django 5.1.1 on 2024-10-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_name_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='product_name',
        ),
    ]
